### ISSUE TITLE
Adding image to markdown block makes finding disappear

### ISSUE THREAD

**Issue by CUBE-DT** [Syslifters/sysreptor#103]
When uploading an image within a markdown block, the entire finding seems to disappear when generating the report.

Without the image:
![image](https://github.com/Syslifters/sysreptor/assets/141190306/32aac737-d508-4cd0-83e9-7ef3f4bf1c8f)

With the image:
![image](https://github.com/Syslifters/sysreptor/assets/141190306/3867cdda-b7fe-4a98-b41f-8481c2b2895e)

Block where the image is inserted with the text:
![image](https://github.com/Syslifters/sysreptor/assets/141190306/9ac41148-624b-49c9-b09a-f013e65842a3)

**Comment by MWedl** [comment]
Hi,
the rendering problem is most likely related to CSS rules. 

There is currently a bug in weasyprint (HTML to PDF rendering library) where CSS `max-width` rules are not applied correctly for images inside tables. However, I'm not sure if this is related to your bug or if it is another problem. Could you check if adding one of following CSS rules helps:
```css
table img {
  width: 100%;
}
img {
  display: block;
}
```

**Comment by CUBE-DT** [comment]
Adding the rule hasn't helped. As a temporary workaround, i've added {width="40%"} (or any percentage really) until it renders correctly.

**Comment by CUBE-DT** [comment]
It actually seems like if the table and the images span over a single page, the entire table disappears. First image is after i've shrunk the pictures to fit into a single page while the second is if i made them a bit bigger so that the table spans across two pages.
![image](https://github.com/Syslifters/sysreptor/assets/141190306/fa1bc645-91c7-4fdf-8f41-24dce886bcf4)
![image](https://github.com/Syslifters/sysreptor/assets/141190306/b5365424-e127-4ba6-8a26-1a70cba7d1cc)

**Comment by MWedl** [comment]
Bad to hear that the fix did not work. I was not able reproduce the bug where the whole table disappears. Without the CSS and HTML for the table it will be hard to find the problem. Would it be possible if you could provide us your design such that we can reproduce and debug the issue. You can also send it to us in private (see https://docs.sysreptor.com/contact-us/).

**Comment by CUBE-DT** [comment]
Sent the design to hello@syslifters.com

**Comment by MWedl** [comment]
The bug is not specific to images inside tables. If any table content spans more than one page (e.g. long text), the whole table disappears. The problem was that in the HTML markup of the table, all rows were wrapped inside a `<thead>` tag. On pagebreaks we try to put the rows of `<thead>` on every page. However, since the table header itself is bigger than a page and contains a pagebreak, rendering of the table breaks because it does not know how to handle it. In order to prevent this bug, remove the `<thead>` tag from the table.

Buggy table:
```html
<table>
    <thead>
        <tr>
            <th>Description</th>
            <th><markdown :text=finding.description" /></th>
        </tr>
        <tr>...</tr>
        <tr>...</tr>
    </thead>
</table>
```

Fixed table:
```html
<table>
    <tr>
        <th>Description</th>
        <th><markdown :text=finding.description" /></th>
    </tr>
    <tr>...</tr>
    <tr>...</tr>
</table>
```

Additionally, you should also add following CSS rule to allow page breaks inside table rows. The default behavior is to avoid page breaks, which produces better-looking results for small table rows. However, since your table contains large rows with content spanning multiple lines or pages, it would look better to avoid page breaks. Or you could target specific large tables or rows via CSS classes to mix breaking styles in your design.

```css
tr {
    break-inside: avoid;
}
```
