### ISSUE TITLE
PDF Rendering Error

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#108]
Hi team.

I've suddenly started to get 
![Opera-2023-10-10 at 15 19 31@2x](https://github.com/Syslifters/sysreptor/assets/3596242/2e392cd6-3037-477c-9b14-6965477da335)

In my project...

I cannot render any PDF anymore :'(

There's nothing showing in the logs.

**Comment by vysecurity** [comment]
Is there an upper limit on the number of vulnerabilities?

**Comment by vysecurity** [comment]
Is there a 60 second rendering timeout?

**Comment by vysecurity** [comment]
It's a big problem because I can no longer render my PDF...

**Comment by aronmolnar** [comment]
We're already looking at the issue.

There is a timeout (soft 55 seconds, hard 60 seconds) which should only be enforced in the cloud.  
We have not yet managed to reproduce it but we see if we can provide you a temporary fix.

**Comment by MWedl** [comment]
The 60 second rendering timeout does not seem to be the problem, because it is not applied for the default self-hosted setup. When using a separate docker container as rendering worker, the timeout gets applied. Using a separate worker is not documented, though. So I assure you did not configure it.

Here are other ideas what could cause the rendering failure:
* request timeout in reverse proxy: Try to render the PDF by accessing SysReptor without the reverse proxy. If this works, increase the request timeout.
* out of memory: PDF rendering is a CPU and memory-intensive operation, especially when many images are included.

**Comment by vysecurity** [comment]
I'll give it a try and see how to fix it. My memory is always 4GB remaining free so I don't think it's the problem.

**Comment by aronmolnar** [comment]
Then it might really be an nginx proxy timeout: https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout

**Comment by vysecurity** [comment]
A lot smoother and successfully generates after removing this timeout.

**Comment by aronmolnar** [comment]
Oh great!
