### ISSUE TITLE
Footnote goes to the next page

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#111]
In the Margherita demo report, footnotes are not printed on the same page, but on the following.

```
Text text^[I'm a footnote [link](https://example.com)] text.
```

![image](https://github.com/Syslifters/sysreptor/assets/25219407/b30cd4c8-01ef-45ae-838c-53df5b6847aa)

(This does not happen for the Calzone Report)

**Comment by MWedl** [comment]
The problem seems to occur when the footnote area takes up too much vertical space. In the base styles we have `@footnote { padding-top: 1em; }` to add some space on top of the footnote area. This seems to be too much. When we decrease it to `0.5em` footnotes are rendered correctly on the same page. I think the reason why footnotes work in the Calzone Design, is because there the font-size is decreased leaving more max-space for the padding.

We will update the base styles in `/assets/global/base.css` to prevent footnotes from appearing on the next page.

**Comment by MWedl** [comment]
Base styles fixed in https://github.com/Syslifters/sysreptor/releases/tag/2023.136
