### ISSUE TITLE
Do not rerender at publish and move download button

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#114]
Does it make sense to move the download button to the PDF viewer?

![image](https://github.com/Syslifters/sysreptor/assets/25219407/e21138c4-2d4a-4d47-8c7f-8f31128e6805)

We could also add a button to open the report in a new tab.  
This would also remove the necessity to rerender the report after preview (or does this have a deeper meaning?).

/cc @cmahrl

**Comment by MWedl** [comment]
The PDF preview is embedded in an `iframe`.  In order to download the PDF with the correct filename from user input left, we need to pass the filename to the `iframe`. This is certainly doable e.g. with `postMessage`. 

If the PDF should be encrypted, we still need to re-render it because PDF encryption is performed server-side.

**Comment by aronmolnar** [comment]
We discussed this internally and we will refrain from doing this.  
If the report should be encrypted it would have to be re-rendered.

If there is a save button in the menu of the PDF viewer (which would save the PDF in plain text), while encryption checkbox is ticked, the pentester might think he saves an encrypted document, which in fact he doesn't.

This is why we leave it as it is.
