### ISSUE TITLE
Referencing issues: Preview vs Rendering

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#115]
When referencing issues, the markdown preview successfully shows references, even though they are not entirely correct (in this case it has a trailing slash):
![image](https://github.com/Syslifters/sysreptor/assets/25219407/a7dc51ce-d871-4c6f-8d81-42b1e52475fe)

When rendering the report, the reference fails (displayed as a warning that the reference was not found).

The preview should probably only work if the reference has the correct syntax.

**Comment by MWedl** [comment]
The preview works as intended. It also cannot resolve the finding. If the preview does not know an referenced ID, it displays a generic placeholder instead of the finding title.

![image](https://github.com/Syslifters/sysreptor/assets/29510012/164e9211-e314-4dd4-a1f7-95c796902bf3)

We cannot display warnings in the preview because we do not know all IDs available in the final PDF. Some IDs may be defined dynamically in the HTML/Vue template of the Design or even in other markdown fields. The reference warnings during PDF rendering are generated late in the rendering after evaluating Vue template expressions when we have access to the final HTML.
