### ISSUE TITLE
Commenting on text

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#124]
We currently allow users to use the keyword "TODO" for writing remarks on text. SysReptor counts those TODOs and displays a warning.

![image](https://github.com/Syslifters/sysreptor/assets/25219407/b488e5ce-3128-4091-bbc1-2e6a15a852d3)

It would be nice to allow comments as metadata (also receiving this regularly as customer feedback) . I looked at notion how they solved this.

They allow selecting the text and select "comment" via a menu bar (we could add this to the markdown editor's menu bar).
![image](https://github.com/Syslifters/sysreptor/assets/25219407/9a94c55f-2a96-4142-a991-fd0b8ce8c580)

The comment can then be written into an overlay text box.

![image](https://github.com/Syslifters/sysreptor/assets/25219407/d7d5d014-18be-4f22-962d-5398a7ae450e)

They then display a comment symbol and the number of comments (and replies) in this line at the right hand side.

![image](https://github.com/Syslifters/sysreptor/assets/25219407/6cb892ab-8acb-46a9-9e6d-b499223ab681)

The comment contains the referenced text (this is a static reference - if you delete "Number 1", the comment remains the same) and a thread of comments.

![image](https://github.com/Syslifters/sysreptor/assets/25219407/fc8efd99-2b6b-4472-8c89-a99e11711407)

To limit complexity of this we might want to limit this functionality to markdown fields.

**Comment by Moneysac90** [comment]
However, you can not apply a comment to the current text as implemented in word. 

![image](https://github.com/Syslifters/sysreptor/assets/20662108/52198e16-e6ff-4641-bf2f-0da7a1f1448c)

As you can see in the picture above a user can click on "annehmen" (german for apply). A reviewer can therefore write some text he assumes to be better and the tester can choose to apply it. This is important in some cases since the reviewer is missing context from the pentest.

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.55
