### ISSUE TITLE
Code block alignment

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#14]
Hi there,

Any idea how to make this code block align with the rest of the text on the right side?

![Opera-2023-05-11 at 16 27 51@2x](https://github.com/Syslifters/sysreptor/assets/3596242/58b66573-5b0f-48f2-8f88-033183a94802)

**Comment by MWedl** [comment]
Hi, thanks for reporting this design bug.

The overflow is caused by a CSS rule applied by the markdown rendering component. This rule sets `width: 100%` of code blocks. This causes a conflict with the `padding: 0.2em` CSS rule in the Calzone Design.

We will remove the conflicting rule in the next release :)

As a workaround you add following CSS to your design:
```css
pre code {
    width: auto !important;
}
```

After updating the global design, make sure to refresh the design in the project settings. Projects use a snapshot of the original design such that design updates do not break or change the rendering of existing PDF reports.

**Comment by vysecurity** [comment]
Thanks for helping! :-)
