### ISSUE TITLE
Guest user restrictions not working

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#148]
Hi,
it looks like the guest user restrictions outlined in https://docs.sysreptor.com/setup/configuration/#guest-users are not working as intended. If I disable all options in app.env a user with the `Guest` role can still create and import Projects.

app env:
```
GUEST_USERS_CAN_CREATE_PROJECTS=False
GUEST_USERS_CAN_IMPORT_PROJECTS=False
GUEST_USERS_CAN_UPDATE_PROJECT_SETTINGS=False
GUEST_USERS_CAN_DELETE_PROJECTS=False
```

Version: 2023.142 (Professional)

**Comment by MWedl** [comment]
Hi, thanks for reporting this. There is a bug while loading these configurations from environment variables in settings.py. The env variables are not converted to boolean, instead they are loaded as strings. This causes permission checks to succeed because string `"False"`  is a truthy value in python. 

The actual permission checks work as expected and prevent access when the settings contain a falsy value. We will fix the boolean type conversion in the next release.

As a workaround, you can set these configurations to an empty string:
```
GUEST_USERS_CAN_CREATE_PROJECTS=
GUEST_USERS_CAN_IMPORT_PROJECTS=
GUEST_USERS_CAN_UPDATE_PROJECT_SETTINGS=
GUEST_USERS_CAN_DELETE_PROJECTS=
```

**Comment by firefart** [comment]
@MWedl thanks tested the workaound and it works - the buttons are visible but there is an error on saving.

Maybe it's also possible to hide the buttons in the gui if project creation is disabled for the current user role?

**Comment by aronmolnar** [comment]
Yes we should rather grey them out

**Comment by MWedl** [comment]
Let's track disabling buttons in the UI in a separate issue: #152

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2023.145
