### ISSUE TITLE
[feature request] naming assets when pasted

### ISSUE THREAD

**Issue by GrylledCheez** [Syslifters/sysreptor#155]
When I paste an image from my clipboard, the first image is called `image.png`, and each subsequent image has a pseudo random number afterwards.

It would be nice to have the option to name the image as I'm pasting it, and have the system NOT allow me to reuse a name to avoid clobbering.

**Comment by MWedl** [comment]
Hi,
renaming is currently only possible in the API. We have not yet built an UI for it. The API Endpoint to rename images is `PATCH /api/v1/pentestprojects/<project-id>/images/<image-id>/`. 

A big challenge for renaming images in the UI is when images are referenced in multiple findings and notes. When renaming these references should also be updated to not break PDF rendering. However, findings might currently be locked and edited by other users. 

In order to provide reliable renaming and updating of all references, we first need to get rid of locking and be able to support updating parts of the text while users are currently editing. Implementing concurrent editing via websockets (see #78 ) would solve these problems and be the requirement for this change to work reliably.

**Comment by GrylledCheez** [comment]
What if you stored the images as a sha-256 or similar hash be the key, then have the "name" be the visible link?

You could reference by the friendly name or the hash name like in a github comment.

**Comment by MWedl** [comment]
There would be a discrepancy between the text in the markdown editor (reference by ID) and the preview (reference by name). Using ID references removes information from the link for named images (for pasted images with name "image-*" it stays the same).

**Comment by aronmolnar** [comment]
You can name images as you want by copying and pasting an image file (instead of the image itself).

![image](https://github.com/Syslifters/sysreptor/assets/25219407/c40d80b9-31cf-477a-a183-91e2a5a92fa0)

The filename is then used for storage.
