### ISSUE TITLE
[Feature Request] - Add HTML export option button.

### ISSUE THREAD

**Issue by danperezasensio** [Syslifters/sysreptor#158]
I would like to be able to download the report in HTML format.
This would also solve some PDF inherit problems, such as copy-paste of codeblocks respecting spaces and new lines.

**Comment by aronmolnar** [comment]
We refrained from doing this so far because you wouldn't be able to use the HTML easily. The report HTML is generated in a headless Chrome browser on the server side and then passed to Weasyprint for PDF rendering.

If we left out the Weasyprint step and give you access to the HTML, you could not open it in your own Chrome browser to render a nice PDF report, because Chrome does not implement many CSS printing directives.

You would need to render it yourself with Weasyprint.

If we would allow you to make adaptions to the HTML and then paste it back to SysReptor to pass it to Weasyprint, we have the issue that you would not be able to update your report via the report fields (e.g. you couldn't add one more finding, or fix a typo via the markdown text field).

**Comment by pwnpanda** [comment]
This would be a great way to debug the raw HTML, which is a case we have ran into multiple times. Would be nice to either be able to view the raw HTML being sent in to the PDF generator, or having the option to export it for debug purposes. Especially when using a lot of customizations to the template reports.

Is this something you would consider implementing @aronmolnar ?

As a side note: Thanks a lot for making a great product - it is really nice!

**Comment by aronmolnar** [comment]
We decided to not provide the HTML due to several complex reasons.

The HTML has ~5MB of scripts and imports prepended, and all images are embedded as base64 which makes the HTML hard to use. It provides only minor advantages in debugging during designing.

We're happy to help resolving issues in your designs if you just open a ticket here.
