### ISSUE TITLE
[feature request]  report name template

### ISSUE THREAD

**Issue by GrylledCheez** [Syslifters/sysreptor#165]
Add a field for a report name template.

I.e
`{report_type}_{last_name}_{version} _{date}.pdf`

The date field should use the strftime spec.

**Comment by aronmolnar** [comment]
We discussed this feature request interally months ago. This is more complex than it seems because in the context of our web application, we cannot reliably resolve the variables. For PDF rendering, they are resolved in the headless Chrome browser that runs on the server side for rendering the PDF.

The efforts are quite big compared to the benefits. This is why the issue hasn't made it to our roadmap so far.

Our current recommendation is to print your report title to the PDF report (e.g. in the footer) and to copy it from there.

**Comment by aronmolnar** [comment]
We received an alternative suggestion that we could implement: We could use the report title as the filename.
