### ISSUE TITLE
Pluralize words

### ISSUE THREAD

**Issue by Alex6440** [Syslifters/sysreptor#177]
Hello,

Is it possible to use pluralize like thise ? [https://011.vuejs.org/api/filters.html#pluralize](url)

Thanks :)

**Comment by MWedl** [comment]
Hi, 
unfortunately it is not possible to pluralize with the pluralize filter anymore, because Vue 3 deprecated the template filter syntax. There are multiple alternative solutions which require installing new libraries. The most commonly used library is Vue I18n.

Where exactly should be pluralized? Do you want to use pluralize words in report designs or should we pluralize in the web interface?
