### ISSUE TITLE
Extract Report Design from Exported Report

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#179]
Is there any way to extract the report design from an exported report?

After re-importing the report, there is no new design made. However copying out each section and making a new design seems to have errors too. I was wondering if there's any way to just import a design that can be extracted from the report export?

**Comment by MWedl** [comment]
The imported project-specific designs are not displayed in the list of global designs, because that would be quite spammy and bypass the designer-permissions (which allows creating global designs for everyone to see and use).

It is possible to copy the imported project-specific design to a global design that is visible in the design list. In the web interface go to Project Settings -> Design (click right arrow besides design selection) -> Design Settings -> Duplicate (in additional actions menu, next to save button).

**Comment by vysecurity** [comment]
This worked great @MWedl !
