### ISSUE TITLE
Newb link question

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#213]
Hello,

In the docs site I see help guidance on making links appear as regular text, but should links in my report be clickable by default?  Or do I need CSS to get them to become links?  Even if I write them as `[markdown link](https://somewhere.com]` they don't show up as clickable in the PDF output.

Thanks,
Brian

**Comment by MWedl** [comment]
Links should be automatically clickable if they have a valid target. CSS can be used to style the appearance of the link text, but it should always be clickable.

Markdown links can only be rendered in a markdown context. When you use a markdown field make sure to render it like that: 
```html
<!-- Markdown from variable -->
<markdown :text="report.markdown_field" />

<!-- Inline markdown in HTML -->
<markdown>
  [markdown link](https://example.com)
</markdown>

<!-- Native HTML link (outside of markdown context) -->
<a href="https://example.com">HTML link</a>
```

**Comment by 7MinSec** [comment]
Hi, I looked at this on a report I wrote today and I had a link to an OWASP site just in plain text in the references area of a finding.  When the PDF was exported, the link indeed was clickable (but not underlined, sounds like I need to do CSS to make this happen) but the link itself went to https://pdf.sysreptor.com/HSTS%20Cheat%20Cheat%20(https:/cheatsheetseries.owasp.org/cheatsheets/HTTP_Strict_Transport_Security_Cheat_Sheet.html).  

I checked in the designer and I have this references area set as type "list" - at the bottom of the screenshot is the .json I use to import this finding:

![image](https://github.com/Syslifters/sysreptor/assets/17596787/afbdd1df-e5d1-4973-b050-cfaee3bf847b)

I tried making the link format be `a href` or follow the markdown format, but on the PDF the text would appear "as is" and wouldn't actually be a proper clickable link.  I can't remember but I think I was having some sort of import problem if I changed the import type from "string" to something else.

**Comment by MWedl** [comment]
The problem is in how the link is rendered in the HTML/Vue template.

I suppose you use following code snippet from the demo designs:
```html
<ul>
  <li v-for="reference in finding.references2">
    <a :href="reference">{{ reference }}</a>
  </li>
</ul>
```
This code assumes that all references are links to websites. It does not support text+link format like in your screenshot. In your report, the `href` attribute is set to a regular (non-link) text `HSTS Cheat Sheet (https://cheatsheetseries.owasp.org/)`. Since the `href` does not start with a scheme prefix (e.g. `https://`), it treats `href` as a relative link and prepends the base URL.

I would recommend to include references as markdown. This allows you to use markdown-style links `[Example](https://example.com)`. You do not have to change the field type of `references2` to markdown, it can still be a string field.
```html
<ul>
  <li v-for="reference in finding.references2">
    <markdown :text="reference" class="markdown-inline" />
  </li>
</ul>
```

**Comment by 7MinSec** [comment]
Very cool that did it and the links look beautiful :-).  Thank you!
