### ISSUE TITLE
Expose and document backend REST API requests

### ISSUE THREAD

**Issue by syn-4ck** [Syslifters/sysreptor#219]
To automate tasks envolving the report generation, it could be a good idea expose and document the API:

- Report management: create, update, delete reports 
- Insert, remove finding template into report
- User management: create, update, delete users
- ...

This feature can improve the iteraction between a script or other software and SysReptor.

**Comment by aronmolnar** [comment]
The API is there because sysreptor is a single page application and is used by our JavaScript frontend.

It can be browsed through via the browser (via /api/v1/) where you can discover all endpoints.

It is, however, not meant to be stable. There can be and will be breaking changes and this is why we don't offer an official documentation.

The better solution is to provide the api methods from reptor that we keep up to date. I'm not sure how well this works at the moment but I think this should be the way to go.

**Comment by syn-4ck** [comment]
Understood! I saw the full API in https://demo.sysre.pt/api/v1/utils/swagger-ui, so I think it's enough
