### ISSUE TITLE
Renaming a report is not reflected in the title

### ISSUE THREAD

**Issue by pwnpanda** [Syslifters/sysreptor#223]
### Expected behaviour:
The title in the generated PDF is updated, when the project settings is changed to have a new name.

### Current behaviour:
The title in the generated PDF does not change and cannot be changed after creating a project

### Steps to reproduce:
1. Create a project
2. Generate PDF
3. Rename the project using the settings-tab
4. Generate the PDF and observe the title has not changed

### Software Version:
2024.8

**Comment by MWedl** [comment]
Hi,
there exists a separate input field in a report section for the report title used in PDF rendering. When creating a project, the title field is set to the same value as the project name. We deliberately use two separate fields so that you can use an internal project name and a pretty customer-facing title for PDFs.

![image](https://github.com/Syslifters/sysreptor/assets/29510012/c3030ae9-c42e-4d5c-91a6-f61b846e4012)
