### ISSUE TITLE
Curly braces escape

### ISSUE THREAD

**Issue by valrdclr** [Syslifters/sysreptor#228]
Is it possible to escape curly braces like "{{" from the findings?
If I want to use them inside the findings, it will crash the report generation because it thinks you want to insert Vue variables (even if I put them in the code quotes)

So far tried to escape with double curly braces and backslash but it doesn't work.

**Comment by aronmolnar** [comment]
Sure you can use the `v-pre` directive: `<span v-pre>{{ this will not be compiled }}</span>`.

https://vuejs.org/api/built-in-directives.html#v-pre

**Comment by MWedl** [comment]
Currently, escaping curly braces is very tricky. Two consecutive curly braces are interpreted as vue template syntax. 

In the HTML template of designs, you can use `<span v-pre>{{ test }}</span>` or `&lcub;&lcub; test &rcub;&rcub;`. In markdown, however, these solutions do not work because of markdown pre-processing.

The generic solution that also works in markdown fields is:
```html
{&ZeroWidthSpace;{ test }}
```

We should definitely improve escaping curly braces. My preferred escape syntax would be `\{\{ test \}\}`. Additionally we should allow `v-pre` directives in markdown and preserve `&lcub;` and `&rcub;` HTML entities in markdown fields.

**Comment by valrdclr** [comment]
> Currently, escaping curly braces is very tricky. Two consecutive curly braces are interpreted as vue template syntax.
> 
> In the HTML template of designs, you can use `<span v-pre>{{ test }}</span>` or `&lcub;&lcub; test &rcub;&rcub;`. In markdown, however, these solutions do not work because of markdown pre-processing.
> 
> The generic solution that also works in markdown fields is:
> 
> ```
> {&ZeroWidthSpace;{ test }}
> ```
> 
> We should definitely improve escaping curly braces. My preferred escape syntax would be `\{\{ test \}\}`. Additionally we should allow `v-pre` directives in markdown and preserve `&lcub;` and `&rcub;` HTML entities in markdown fields.

The ZeroWidthSpace doesn't work if the payload is inside "code" markdown. However I found a workaround and I'm just copying zerowidth element manually: https://zerowidthspace.me
Seems like the bytes are not reflected in the pdf and it is stripped. But still a proper escaping would be good in the future :). Thanks

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.28

Curly braces can now be escaped with backslashes. Additionally, curly braces inside markdown code blocks are never interpreted as Vue template variable expressions.
