### ISSUE TITLE
[Feature Request] Validate Embedded Links during Report Generation

### ISSUE THREAD

**Issue by c-leitner** [Syslifters/sysreptor#241]
It would be beneficial if links embedded within reports could be automatically validated during the report generation phase. Specifically, the system should check the HTTP status code of each link. If a link does not return a status code of 200, indicating a successful connection, a warning should be displayed. This feature would enhance the reliability of the report content by ensuring all embedded links are active and accessible at the time of report generation.

**Comment by aronmolnar** [comment]
Hi Clemens,
This is, unfortunately, not possible due to security reasons.  
Report generation happens in a dedicated environment and has no access to the Internet. We have more information about this restriction [in our docs](https://docs.sysreptor.com/insights/security-considerations/#server-side-request-forgery-prevention).

You could, however, create a custom reptor plugin that fetches the links from your report data and check the validity of the URLs, e.g., via Python requests.

**Comment by c-leitner** [comment]
Okay, thanks for the explanation. That makes sense. I think I will solve it with a custom plugin.
