### ISSUE TITLE
Notes not usable when using a reverse proxy without websocket support

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#243]
When using a reverse proxy without websocket support it's not possible to access the notes section. You always get `Server connection lost` when trying to access the notes as the websocket connection fails.
It would be nice if websockets are optional and the note editing works without the collaboration feature in this case.

**Comment by jdelta1** [comment]
Same issue here. Should be a way to configure your reverse proxy to support websockets connections, I'm assuming you're using nginx. I'll update here if I get it working.

**Comment by firefart** [comment]
@jdelta1 the needed changes should be documented here: https://github.com/Syslifters/sysreptor/discussions/230

In my case it's sadly a corporate requirement to use a central reverse proxy system which does not support websockets yet, so I have no way to enable it by configuration

**Comment by aronmolnar** [comment]
We currently have no possibility of a failover to bypass the web sockets. The only short-term solution is to downgrade to version [2024.20](https://github.com/Syslifters/sysreptor/releases/tag/2024.20) (it is, however, important to use an up-to-date reverse proxy with this version, because there is a vulnerability in Gunicorn if attackers can access the web server without reverse proxy in front of it).

We will discuss next week, how we can handle the issue for you @firefart.

@jdelta1 nginx has supported websockets for more than ten years, even though it's not always easy to configure it.
I just set up a fresh install of SysReptor following our [installation guide](https://docs.sysreptor.com/setup/installation/) and the [setup steps for nginx](https://docs.sysreptor.com/setup/webserver/#nginx) and the websocket support worked.  
It might be easier to go with [Caddy](https://docs.sysreptor.com/setup/webserver/#caddy-recommended) if that's an option for you.

**Comment by MWedl** [comment]
Hi @firefart we decided to implement a HTTP fallback when no websocket connection can be established. Please note that this fallback will not have the same latency as real websocket connections. You might encounter higher delays until changes are synced.

**Comment by MWedl** [comment]
Implemented HTTP fallback in https://github.com/Syslifters/sysreptor/releases/tag/2024.40
