### ISSUE TITLE
[Feature Request] Add German-style quotation marks („“) to the Markdown editor menu

### ISSUE THREAD

**Issue by c-leitner** [Syslifters/sysreptor#252]
It would be helpful to have an option to include German-style quotation marks („“) in the Markdown editor menu. Alternatively, these could automatically replace standard quotation marks (" ") whenever the language setting is German, adapting to fit the current language style, similar to how it is handled in Word.

**Comment by aronmolnar** [comment]
In SysReptor Professional, you can use the spell check and enable picky mode (see https://docs.sysreptor.com/setup/configuration/#spell-check), which will also report style issues, like smart quotation marks.

You can use the improvement dialog to apply the correct quotation marks:

![double_quotes](https://github.com/Syslifters/sysreptor/assets/25219407/d12d652a-36b9-4d80-ae3f-511d860dbf67)


For those using the Community Edition, there are shortcuts to insert the correct quotation marks.

**Linux**
Lower: Alt Gr + V
Upper: Alt Gr + B

**Windows**
Lower: Alt + 0132
Upper: Alt + 0147

**Mac**
Lower: Alt + ^
Upper: Alt + 2


We decided against further automizations because this type of quotation marks is not what we want in each case. It might be annoying to have to copy/paste simple double quotes, if needed.
