### ISSUE TITLE
Websocket Issue

### ISSUE THREAD

**Issue by carter-falconops** [Syslifters/sysreptor#256]
Hello,

I recently updated my instance to 2024.40 from 2024.30 and noticed that I am constantly getting the HTTP fallback message due to the client not being able to connect to the websocket. This was not an issue for my deployment on 2024.30 and the websockets worked fine. 

I am using the suggested nginx config and have not changed anything in my configuration from 2024.30 -> 2024.40. All of the errors in the chrome dev console are reporting from this line https://github.com/Syslifters/sysreptor/blob/66bc4fe2c108a69a25970056901d6f9384b32c1c/frontend/src/utils/collab.ts#L172  

The error specifically says 'Failed to establish connection' however I have confirmed that the websocket is open via websocat. Any advice on what I may be doing wrong?

**Comment by aronmolnar** [comment]
Hi Carter,

It is probably due to the fix for a security vulnerability we have had since the introduction of WebSockets (see https://github.com/Syslifters/sysreptor/security/advisories).
It can probably be fixed if you configure the ALLOWED_HOSTS in your app.env (https://docs.sysreptor.com/setup/configuration/#allowed-hosts).

**Comment by carter-falconops** [comment]
That was it! Thank you, I appreciate the help.
