### ISSUE TITLE
Markdown underlining doesn't appear to work

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#26]
I am trying to underline some text in markdown:

```
1. __Testing__: hello world
2. __Testing 2__: hello world 2
```

but it doesn't work.

Even tried `<u>test</u>` but doesn't work.

**Comment by vysecurity** [comment]
Seems I can get it to work with:

```
<span style="text-decoration:underline">this</span>
```

But this is really bad LOL

**Comment by MWedl** [comment]
Markdown (CommonMark Specification) does not have a syntax for underline. `__text__` is the same as `**text**` and makes text bold. `<u>` would be the correct syntax.

However, it seems that our HTML sanitizer removes `<u>` tags because they are [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u). Browers still support them and render them correctly as underline.
I think using `<u>` tags is more convenient than the awkward `<span style="text-decoration: underline">` syntax, even though they are deprecated. I will whitelist `<u>` tags in the HTML sanitizer in the next release.

**Comment by noraj** [comment]
I agree, `__text__` is for bold and `_text_` for italic. There is no underline in markdown. You have to use something in HTML. As a temporary ~~dirty~~ workaround `<ins>text</ins>` can be diverted to underline more easily than `<span style="text-decoration:underline">this</span>` until `<u>` is unblocked.

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/0.87
