### ISSUE TITLE
reportcreator_api.archive.crypto.base.CryptoError: Either a key or a multiple available keys must be given

### ISSUE THREAD

**Issue by wwwiesel** [Syslifters/sysreptor#273]
Hello,

after Update and reinstalling i am getting

reportcreator_api.archive.crypto.base.CryptoError: Either a key or a multiple available keys must be given

Any chance to get my data back?

Btw... Any chance to get sysreptor working without docker? i am not a fan of docker.

**Comment by MWedl** [comment]
Hi,

the error means that no decryption keys are configured in `ENCRYPTION_KEYS`. The old SysReptor version had keys configured. Could you please check if you still have the old config file before the update (`deploy/app.env`). See also #234

> Btw... Any chance to get sysreptor working without docker? i am not a fan of docker.

Nope. We only support docker officially, because it is easier to manage dependencies. With docker containers we can ensure that every build uses the same dependency versions and are more flexible in updating or adding new dependencies.

**Comment by MWedl** [comment]
Yes, in order to disable MFA, remove all MFA methods (Security Key, TOTP, Backup Codes) in your user profile's security settings.
