### ISSUE TITLE
"Could not establish WebSocket connection" - improve update.sh script

### ISSUE THREAD

**Issue by emizzz** [Syslifters/sysreptor#281]
By doing the update through the `update.sh` script, the following changes were necessary to avoid the "Could not establish WebSocket connection" error already reported in issues #280 and #256:

- adding `ALLOWED_HOSTS="mydomain"` in the `app.env` file;
- adding `proxy_set_header Upgrade $http_upgrade;` and `proxy_set_header Connection "Upgrade";` in the `sysreptor.nginx` file (same for Caddy?);

It would be helpful if `update.sh` would also handle these new parameters by itself without human intervention.

Hope this helps :)

**Comment by aronmolnar** [comment]
Thanks for summing up the settings.

An automatic handling is, unfortunately, impossible, because
1. the update script cannot know the ALLOWED_HOSTS
2. nginx (and its config) is not part of SysReptor and managed by users themselves

We communicated the nginx update requirements via several channels (and in #230 ).  In Caddy (our recommended web server), no changes are required for allowing web sockets.  
The ALLOWED_HOSTS requirement came up in a later update due to a vulnerability and is not required in all setup variants.
