### ISSUE TITLE
Inconsistent spell checking

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#288]
Hello,

I'm relatively new to having a pro account and my understanding is spell check should be automatically on as I go about writing reports, right?  I'm noticing several instances like this where the incorrectly spelled word will *eventually* get underlined, or might get underlined if I move to a different section of the report and come back again.

![image](https://github.com/user-attachments/assets/93ba995c-5f7c-4289-956c-bafe07f7cd9f)

Is there anything I need to check or hard-set in the config file(s)?  I see in my instance that I'm a couple versions behind the latest so I'll do an upgrade today too and see if that helps.

Thanks,
Brian

**Comment by aronmolnar** [comment]
Here's some guidance to troubleshoot. Maybe you can provide more information after looking through all steps?

The spell check requires an additional docker container.
Users who upgraded from Community might not have started this container. You can check if it runs using `docker ps` and see if the "sysreptor-languagetool" container is up and running (and healthy).

Additionally, the Spell check could be disabled using this button in markdown editors:

![image](https://github.com/user-attachments/assets/ae5481db-be4c-4559-a670-fdb92236ee08)

(The white frame means it's enabled.)

The editor sends your text to the languagetool docker container. You should see this in the network tab of your browser. The return status code should be 200 (otherwise, there is probably an error).

![image](https://github.com/user-attachments/assets/97a2af4c-6b86-4cee-adde-cc01da0da9b5)

I see, however, that the spell check doesn't seem to work within the HTML tags like in your example.

![image](https://github.com/user-attachments/assets/a25167a2-7a1c-44b4-9e4d-96e2dfc4b8a6)

(Line 1 is parsed correctly, line 2 not.)  
We will have a look at this.

In your case, I don't think that is a configuration issue (find spell check related configuration options [here](https://docs.sysreptor.com/setup/configuration/#spell-check)).  
Upgrading to the latest version might also help.

**Comment by 7MinSec** [comment]
Hi there,

Thanks as always for your great help.  Steps I took:

* Upgraded to latest version
* Checked that the `sysreptor-languagetool` is running - we're good there:

![image](https://github.com/user-attachments/assets/360de759-2f80-4c16-878e-1f6c1a62b79c)

* I went into the report I pulled my example from and the auto check was *disabled* - weird, I don't ever remember changing it.

* As I went about typing stuff in regular body fields, spell check kicked in immediately and flagged misspelled words!

* Only thing (which you already noted) is words in `figcaption` don't auto-correct, which would be great if that could happen in a future release.

Unless you want to keep this open for the `figcaption` issue, I think I'm good to go and can close this.

Thanks again,
Brian

**Comment by MWedl** [comment]
The reason why spellchecking words in `figcaption` does not work, is because we do not perform spellchecks inside HTML code blocks, only in markdown structures. This is a limitation of our markdown parser, as we do not further parse the HTML to separate tags from text.

**Comment by 7MinSec** [comment]
OK I'll just keep a close eye on spelling for my captions.  Thanks!
