### ISSUE TITLE
Markdown push to next page

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#29]
Any way to use markdown to specify the `<pagebreak/>`?

**Comment by noraj** [comment]
There is no page break nor in Markdown nor in HTML. I believe this custom tag was introduced to inject a `\pagebreak` in LaTeX.

**Comment by vysecurity** [comment]
Wonder if we can add it to the next version so we can pagebreak within a markdown section... hmmm

**Comment by MWedl** [comment]
In the current version, the HTML sanitizer removes `<pagebreak />` elements. We will add them to the whitelist in the next version.

`<pagebreak />` is a wrapper-component for a CSS rule. You can use following HTML inside markdown as a workaround:
```html
<div style="break-after: page;"></div>
```

**Comment by vysecurity** [comment]
> In the current version, the HTML sanitizer removes `<pagebreak />` elements. We will add them to the whitelist in the next version.
> 
> `<pagebreak />` is a wrapper-component for a CSS rule. You can use following HTML inside markdown as a workaround:
> 
> ```
> <div style="break-after: page;"></div>
> ```

It didn't seem to work for me.

**Comment by vysecurity** [comment]
Worked!

**Comment by vysecurity** [comment]
Is it a bug? I use `<pagebreak>` in a user-defined section and it puts a massive white page then the rest of the content doesn't get shown at all.

**Comment by MWedl** [comment]
To fix this, please use the self-closing tag `<pagebreak />` (with a slash at the end). 

`<pagebreak>` is an opening tag, `<pagebreak />` is a self-closing tag. When using a opening tag, the markdown renderer automatically inserts a closing tag at the end to produce valid HTML (resulting in `<pagebreak><p>remaining markdown text</p>...</pagebreak>`). Since `pagebreak` is a custom component that does not have any content, its child-tags are ignored/discarded during template rendering.

**Comment by vysecurity** [comment]
Thanks!
