### ISSUE TITLE
Best way to handle page breaks?

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#322]
Hello,

First let me start by saying again how much I LOVE sysreptor.  Thank you for this!  It has made pentest reporting fun again.

When I get the finished PDF of a report, I find that overall sysreptor does a great job of handling page breaks.  But there will be times when I'm talking about a finding and then showing a screenshot, and the screenshot pops to the other page, leaving an awkward gap before the page break.

How I've been addressing that now is just going into the image and setting width=75% for example, and just gradually working with that number until the image fits nicely at the end of the original page.

Two questions:

1. Is that the best way to do that right now?
2. If so, as a potential feature request could there be an image auto-resizing threshold that could help content fill the pages more fully?

This is a MINOR issue for sure.  Probably takes me 3 minutes of post-report-writing cleanup.  But sysreptor has made me so fast at writing reports, I naturally just want to go even faster :-)

**Comment by MWedl** [comment]
> Is that the best way to do that right now?

Yes, I this is currently the best way to fit images to pages. We are not aware of any solution how to solve this in print CSS without manually setting image sizes.

> If so, as a potential feature request could there be an image auto-resizing threshold that could help content fill the pages more fully?

Such a auto-resizing threshold would need to be added to the CSS specification and implemented by Weasyprint. This is out of scope for SysReptor. 

The solution for this needs to be implemented in CSS, because only in the HTML+CSS to PDF rendering stage (where CSS rules are evaluated and page layouting happens) we know where page breaks will be added. It is not possible to implement a solution to the Vue template rendering stage because not page break and layout information is available.

**Comment by 7MinSec** [comment]
Makes sense and thank you for the thorough reply, as always!
