### ISSUE TITLE
TypeError: b.startsWith is not a function in design "MYTemplate"

### ISSUE THREAD

**Issue by OlderMutt** [Syslifters/sysreptor#324]
after the update i receive this error on my design:

![image](https://github.com/user-attachments/assets/07fd80f9-7370-4fbc-bbf5-209ddd4d4771)

i don't know what is happened

**Comment by aronmolnar** [comment]
You seem to have an operation in your report design (HTML/VueJS) which is `b.startsWith`.
The variable `b` doesn't seem to have the `startsWith` function (probably because `b` is not a string but for example an object or a number).

Check your design for this function:
![image](https://github.com/user-attachments/assets/8f25af5f-8829-4db0-b0ab-7603eb377d04)
