### ISSUE TITLE
[Feature Request] Suggest vulnerabilities link in markdown fields

### ISSUE THREAD

**Issue by danymat** [Syslifters/sysreptor#331]
When writing a report, we may want to add a link to reference vulnerabilities, such as documented here: https://docs.sysreptor.com/reporting/references/

To improve usability and discovery of this feature, I would like to see a way for sysreptor to suggest a link to be written. The exact way could still be discussed, but here are some ideas:

- A completion system: starting to write `[vulnerability](#` will trigger the list of findings to be selected
- In the WYSIWYG markdown input field, adding an icon (next/on top) to the url icon to add a link to a finding, still selectable.

**Comment by MWedl** [comment]
Thanks for the suggestion. We will add a button to the markdown editor's toolbar to insert finding references.

![image](https://github.com/user-attachments/assets/7a8f7018-42c8-4058-9099-811097621d39)

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.79

**Comment by danymat** [comment]
It works great ! Thanks :)

**Comment by MWedl** [comment]
We do not copy the title into markdown text, because when the title of the referenced finding is updated, the markdown text would not change. When the title is left empty, SysReptor dynamically resolves the finding reference during PDF rendering. By using dynamic references, it is possible to customize the reference format via CSS (e.g. chapter number instead of title).

**Comment by danymat** [comment]
Makes sense !
