### ISSUE TITLE
Show warnings in Designer error list

### ISSUE THREAD

**Issue by richardschwabe** [Syslifters/sysreptor#35]
URL: /designs/7...ea/pdfdesigner/
Browser: Chrome
Setup: Self Hosted docker

I had an issue with the PDF Previewer crashing after a few seconds, even though the auto reload or manual regeneration worked fine. My issues were that I had some HTML tags with the `:id` attribute, rather than the normal HTML `id` attribute. Which is an easy copy/paste or typo mistake.

However, when the PDF Previewer is crashing no error messages are shown. 

For this I suggest to add to the documentation (https://docs.sysreptor.com/designer/debugging/) for self-hosted users to:

1. Open the logging for the `sysreptor-app` container
2. Look for any lines with  `Chromium messages`, this will have error message under the key `message` to investigate any  issues within the template.
3. Another error message to look for starts with `weasyprint`

I guess a long term solution is the implementation of an "error log" or similar that can be accessed during the design phase.

However, some error message are useless i.e:
```
2023-05-19 16:36:02,878 [INFO] root: Chromium messages: [ErrorMessage(level=<MessageLevel.WARNING: 'warning'>, location=None, message='Invalid prop: type check failed for prop "text". Expected String with value "[object Object],[object Object]", got Array ', details='at <Markdown>\nat <Anonymous>'), ErrorMessage(level=<MessageLevel.WARNING: 'warning'>, location=None, message='Component is missing template or render function.', details='at <Anonymous>\nat <Markdown>\nat <Anonymous>')]
```

**Comment by MWedl** [comment]
Thanks for feedback. We will go with the long term solution because would be helpful while designing.

Currently errors are only displayed when PDF rendering failes completely and no PDF is produced. When the Vue template engine ouputs them as warnings, they are just logged. If rendering successds the HTTP response contains the PDF file as binary data. If rendering failes a HTTP 400 response is returned with error data as JSON. In order to provide an error/warning log, we need to change the response such that the PDF and error messages can be returned at once. We could base64 encode the PDF and put it in JSON.

The bigger challenge will be the UI. Currently, errors are displayed in an overlay over the PDF viewer. This kind of disabled the PDF viewer until all errors are resolved. When we also display warnings, warnings should not block the PDF viewer, they should be additional information. We are not yet sure about the error log UI. Do you have any suggestions?

![Screenshot_20230522_074347](https://github.com/Syslifters/sysreptor/assets/29510012/0a87ec76-b3f3-473c-9c89-eae76a0f9380)

**Comment by aronmolnar** [comment]
Can we display the warnings in the overlay and allow the user to (permanently) close it?

![image](https://github.com/Syslifters/sysreptor/assets/25219407/080bc60e-5187-4474-8c49-d2e505d416ed)

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/0.95

SysReptor now reports errors, warnings and info messages during PDF rendering. They are displayed in a warning-bar at the bottom of the PDF preview. If you click it, you can toggle the error/warning list to see details.

![image](https://github.com/Syslifters/sysreptor/assets/29510012/65c70546-14b2-46fc-a272-4cd2d4ca590d)
