### ISSUE TITLE
Empty Login Page after installation

### ISSUE THREAD

**Issue by secure-77** [Syslifters/sysreptor#49]
Hi, 
first of all, nice project! I tested already an early version and wanted now to install the latest version on a new vm.

Installation script works fine but I only get this page without the possibility to login.

![image](https://github.com/Syslifters/sysreptor/assets/31564517/a5f0c360-beba-4e2d-aa73-1e51be63085e)

Network analytics says, that one endpoint cant be accessed (not sure if this is the problem)

![image](https://github.com/Syslifters/sysreptor/assets/31564517/3ff48000-4586-45a5-9d52-37c5b553a17a)

Thanks for any hint!
BR,

Sec

**Comment by aronmolnar** [comment]
This is a bug in the new version. Will fix it asap.

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/0.96

The problem was a bug in the API endpoint that returns instance settings to the frontend. The API always returned an empty list of available authentication providers (this should have included local login with username/password), which is why the frontend rendered an empty login form. 

FYI: The 403 response is expected. This request is used to check if a user currently is logged in or not.

**Comment by secure-77** [comment]
Thanks, with the new version the login is working ❤️
