### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by TheAutisticTechie** [Syslifters/sysreptor#52]
After installing with the install.sh script, I then set up Caddy and generated the keys for Django and encryption. Upon launching a browser to login however I get a 403 error on  `GET .../api/v1/pentestusers/self/` which I believe is normal. When entering the credentials provided from the install script a `login failed` toast comes up. In the console I get a 500 error on `POST ...api/v1/auth/login/` with the below from `toast.js`

```
Request error Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.A (xhr.js:66:7) Login failed 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```
Assuming this is standard for incorrect logins, what would the process be for resetting the password? And is there a step i took that i shouldn't have whilst setting it up?

**Comment by aronmolnar** [comment]
The install.sh script creates the encryption secrets for you.
Did you overwrite the keys?

This would cause the 500 server error because the data from the database can no longer be decrypted.
I'd suggest to delete the docker volumes and reinstall everything, if that's the case.

You could reset your password by going to the `deploy` folder and run `docker compose exec app python3 manage.py changepassword reptor` (but this would probably not help if there are encryption issues).

**Comment by TheAutisticTechie** [comment]
I did indeed overwrite the keys. I've just redeployed now and gotten logged in straight away without a problem :)

Blindly following the documentation without thinking about it, my bad 😅
