### ISSUE TITLE
CSS issue with more than four fields in vulnerabilities

### ISSUE THREAD

**Issue by brunomcuesta** [Syslifters/sysreptor#53]
Hello!
When placing more than four fields in vulnerability the page appears blank and the vulnerabilities are placed on the next page. As if there was a hidden "pagebreak".

![image](https://github.com/Syslifters/sysreptor/assets/816237/24d46753-c765-4b40-b21a-9340ce62a427)

There is no page break in the section and when I place four fields the first vulnerability appears just below the section title. In the image below I commented out the code for the other fields of the vulnerability and the problem disappeared.

![image](https://github.com/Syslifters/sysreptor/assets/816237/9ec84fe0-a792-4366-9c96-035fed4d592f)

Would it be some bug that breaks the page when more than four fields are placed in this vulnerability details section?
Thanks!

**Comment by MWedl** [comment]
Hi!
We have tried to reproduce the CSS issue with the Calzone Demo Design by adding some markdown fields to findings. There it renders as expected without a page break before the headline, even when a finding takes up more than one page.

I think the problem is somewhere in your custom CSS rules. There exist many CSS rules and conditions that may lead to page breaks.

**Comment by brunomcuesta** [comment]
Hello!
I had put a CSS in a DIV to prevent the findings table from being broken by not having space on the page. With this CSS the entire table goes to the next page.

```
.finding-div {
    page-break-inside: avoid;
}
```

This DIV was closing down the last field of findings. By putting it at the end of the table the problem was solved.

Thanks!
