### ISSUE TITLE
Add shortcut for adding new note and finding

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#70]
It might be comfortable to have a shortcut (e. g. Ctrl+N) for adding new notes and findings.

We could add a tooltip at the "Add" button as a hint (e. g. "Add with Ctrl+N")

**Comment by MWedl** [comment]
We cannot use Ctrl+N, because in Chrome this keyboard shortcut is used to open a new window and therefore cannot be handled by JavaScript. I would prefer a shortcut that is not used by browsers (e.g. Ctrl+N,T,... => new window/tab/...) or common in text editing (e.g. Ctrl+C,V,Z,Y => copy/paste/undo/redo).

**Comment by aronmolnar** [comment]
How about Ctrl+Q? (Q for Finding; or Q for Note)
It was used (in the past?) by Firefox to close the browser. (in my up-to-date Firefox browser it does not close with ctrl+q)

(i did not find another shortcut that is easy to hit with one hand and not used by a browser.)

**Comment by aronmolnar** [comment]
Okay, forgot about the poor Apple users.
