### ISSUE TITLE
Finding template language search filter

### ISSUE THREAD

**Issue by noraj** [Syslifters/sysreptor#74]
The endpoint  `/templates/` is a page were all finding templates are listed and a search bar is available with a language filter.

However, the language filter is offering a list with all languages supported by Sysreptor rather than only the languages used.

![image](https://github.com/Syslifters/sysreptor/assets/16578570/fdc70475-f40f-4f8b-a71e-00090d118d3f)

If in my template I use only 2 or three languages I would want to have only those listed on a search filter and not a very long list where I have to scroll among 99% of entries I will never use.

Keeping the language list will all languages supported is required only on the finding creation page (`/templates/new/`).

**Comment by MWedl** [comment]
Currently it is already possible to show only relevant languages by configuring an environment variable (in `deploy/app.env`). This hides all other languages in all UI elements (template search, new template, edit template, project settings, etc.).

For example if you only write templates and reports in English and German, you can configure:
```
PREFERRED_LANGUAGES="de-DE,en-US"
```
It also changes the language order. In the above example, German will then be the default language instead of English.

See https://docs.sysreptor.com/setup/configuration/#languages
