### ISSUE TITLE
Improvement for the review process. 

### ISSUE THREAD

**Issue by Moneysac90** [Syslifters/sysreptor#97]
Reviewing pentesting reports in sysreptor is currently only possible by changing the text directly or by commenting with the "TODO" keyword. 

However, if you work with new employees (especially junior consultants) with less or minimal documentation experience, they need a lot more feedback in order to improve their documentation skills. A good example is the "Track Changes" feature of Microsoft Word. If you change the text, you can see exactly what has changed. This feedback is very important, especially for new colleagues. 
 
One possible solution would be to implement a special review mode that also tracks document changes and comments. This review mode could for example show the original version on the left side and the reviewed version on the right side.

**Comment by ovxrfl0w** [comment]
I would say the idea was also to improve the process slightly. Having a comment system would be a beneficial feature as well.

Let's say a junior person creates a report and gives it to a senior for review. The senior would review it, add comments and give it back so that the junior can fix them. I would say it's more beneficial than having a system where the senior person modifies the report and gives it back to the junior as the other person might not have some context about the tested application.

I think it would be beneficial to add comments for findings + for specific sections like Management Summary (maybe it could be a togglable option in template designer).

**Comment by aronmolnar** [comment]
> I would say the idea was also to improve the process slightly. Having a comment system would be a beneficial feature as well.
> 
> Let's say a junior person creates a report and gives it to a senior for review. The senior would review it, add comments and give it back so that the junior can fix them. I would say it's more beneficial than having a system where the senior person modifies the report and gives it back to the junior as the other person might not have some context about the tested application.
> 
> I think it would be beneficial to add comments for findings + for specific sections like Management Summary (maybe it could be a togglable option in template designer).

This is on our roadmap for H2 2024.

**Comment by MWedl** [comment]
The diff-view is implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.8

Let's track commenting on text in a separate issue: #124
